version: '3'

services:

  hkx-db-2:
    container_name: hkx-db-2
    build:
      context: ops
      dockerfile: mongo/Dockerfile
    expose:
      - 27017

  hkx-back-2:
    container_name: hkx-back-2
    build:
      context: ops
      dockerfile: back/Dockerfile
    volumes:
      - ./back:/var/www/hkx:rw
    links:
      - hkx-db-2
    ports:
      - 127.0.0.1:1337:1337

  hkx-front-2:
    container_name: hkx-front-2
    build:
      context: ops
      dockerfile: front/Dockerfile
    volumes:
      - ./front:/var/www/hkx:rw
    ports:
      - 127.0.0.1:8100:8100